name: summarizer_plugin
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - python-dotenv
    - quart
    - quart-cors
    - requests
    - beautifulsoup4
    - pdfminer.six
    - tiktoken
    - openai
