openapi: 3.0.1
info:
  title: LargeTextSummarizer
  description: A plugin for summarizing large texts from any website. Simply pass on the url given by the user to the api endpoint and a summary will be created. Creating summaries may take some time depending on the length of original source text.
  version: '1.0'
servers:
  - url: https://api.yaoyaopianist.de
paths:
  /summary:
    post:
      operationId: summary
      summary: Downloads HTML or PDF from given url and creates a summary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummaryRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryResponse'

components:
  schemas:
    SummaryRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          description: The url that points to the document that will be summarized.
          required: true
    SummaryResponse:
      type: object
      properties:
        result:
          type: string
          description: The summary of the source document.